services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"

  proxy:
    build: ./proxy
    ports: 
     - "8000:80"