services:
  backend:
    build:
      context: ./backend
    container_name: tictactoe-backend  
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  frontend:
    build:
      context: ./frontend
    container_name: tictactoe-frontend
    ports:
      - "3000:80"

  proxy:
    build: ./proxy
    container_name: tictactoe-proxy
    ports: 
     - "8000:80"